[package]
name = "simplify-mathematica-tex"
version = "0.1.0"
edition = "2021"

[lib]
name = "simplify_mathematica_tex"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.79"
itertools = "0.12.0"
pyo3 = { version = "0.20.2", features = ["extension-module"] }
winnow = "0.5"
